### ISSUE TITLE
Add create new feature with fields pre-filled (for example to use with workforce)

### ISSUE THREAD

**Issue by BoudewijnBoogaard** [Esri/collector-integration#13]
In Survey123 it is possible open a new survey and pre fill form fields. I have managed to get this to work in combination with ArcGIS Workforce by editing the workforce project json in the ArcGIS Online Assistant.

Now I would like to auto create a new feature where I can automatically fill fields like the workOrderID and assignmenttype from workforce.

**Comment by doug-m** [comment]
Thanks for the feedback @BoudewijnBoogaard, this is certainly something on our development road map for Collector.

**Comment by doug-m** [comment]
From a Collector perspective this is implemented on Android and iOS; still on the road map for Windows.

**Comment by doug-m** [comment]
No plans to implement this for Windows.
