### ISSUE TITLE
Collector Callback 

### ISSUE THREAD

**Issue by bnadler** [Esri/collector-integration#18]
I am able to launch Survey123 from Collector, but once the survey is completed, how do I configure the callback to return to Collector?
Below is what I have tried per the documentation on the Survey123 side. once survey123 completes, it returns to the surveys screen, not to collector.

arcgis-survey123://?itemID=###&field:ASSETID={GLOBALID}&callback=arcgis-collector://

**Comment by doug-m** [comment]
@bnadler Collector doesn't currently support a callback mechanism like Navigator or Survey123. To this point Collector's workflow doesn't require a direct correlation between completing an edit and the completion of a given task.  Can you share a bit more about why you are moving between Survey123 and Collector?

**Comment by scapararo** [comment]
Hi Ben,
I am running into the same problem with Collector / Survey123 integration that you describe here. Did you ever find a solution?
Thanks Shawn

**Comment by bnadler** [comment]
Looks like the issue is still open.
I was not able to find a solution other than end-user training.
There was a dependency on Survey123 supporting the callback, then Collector responding to the call.
Perhaps in a later release of Collector this will be resolved.

Check this thread on Geonet 
https://community.esri.com/thread/191106-app-link-callback-to-collector

**Comment by murphy214** [comment]
Solved this by just hacking on uri, it works, maybe still relevant? 

```
arcgis-survey123://itemID=youritemid&callbackprompt=yourappname&callback=app://
```
Someone should put that on Survey123's documentation page?

**Comment by doug-m** [comment]
@murphy214 we've added a similar callback to what is available in Navigator here: https://github.com/Esri/navigator-integration#enable-notifications-when-navigation-completes

This is currently available in our latest iOS beta if you're interested in trying it out.

**Comment by doug-m** [comment]
Available on iOS but not documented here - please use our [doc site](https://doc.arcgis.com/en/collector/ipad/help/deploy-map.htm#ESRI_SECTION1_F7DE2402BA8743E5BFC4A1241072960E) for current status.
