### ISSUE TITLE
Transfer credentials into the collector from another app

### ISSUE THREAD

**Issue by shaharbukra** [Esri/collector-integration#20]
Hi,

Im developing application which does login inside the AGOL,
I was wondering if its possible to open the collector with the credentials from my app.
are there any more parameters which the collector can recieve?

Thanks,
Shahar.

**Comment by doug-m** [comment]
Unfortunately this is not possible, and not something we can support given the security concerns of passing this information via the scheme.  

Currently the parameters we have documented are all that the scheme supports.  If you have other ideas or needs feel free to submit an issue.
