### ISSUE TITLE
URL Scheme in Windows

### ISSUE THREAD

**Issue by ericpoon124** [Esri/collector-integration#24]
Hi, 

I followed your instructions to use the URLScheme for Collector. I was able to get Collector to open with the proper web map loaded in Collector. However, when I tried to use the 'Initiate feature collection and specify attributes' via the use of URLscheme, it doesn't seem to work. I've formatted the URL as follow:

arcgis-collector://?itemID=529d74c0eb7e45f1b1fda69922335ceb&featureSourceURL=https://utility.arcgis.com/usrsvcs/servers/d4d10e45525b4ae0bbdee03cb08876b9/rest/services/SignsCollectorTST/FeatureServer/0&featureAttributes={"Status":Active}

I would like to start feature collection with a Status of Active in collector via the use of URLScheme but it doesn't seem to be working.  I've attached a picture for reference. I am running this in Windows 10 with the Windows Collector App.

Thanks!
Eric

![collector_url](https://user-images.githubusercontent.com/21343859/45170458-cdd02500-b1b4-11e8-8f38-405105d49aac.jpg)

**Comment by doug-m** [comment]
@ericpoon124 this isn't currently implemented for Windows, as documented [here](https://github.com/Esri/collector-integration)

> Support for featureSourceURL and featureAttributes parameters is available in Collector 17.0.3 or later (iOS and Android only).

We will be adding this to an upcoming release for Windows.

**Comment by nferguson2** [comment]
Hi @doug-m,

I have been working with Eric on this issue and have encountered the same activity in iOS and Android. Below are my sample URLs and screenshots of the results in Collector 18.0.2 build 2109 on iOS. 

Encoded URL based on documentation:
arcgis-collector://?itemID=d66e323d4069457697327db5b7151f75&featureSourceURL=https://services.arcgis.com/EgePHk52tsFjmhbJ/arcgis/rest/services/C02169037/FeatureServer/0&featureAttributes=%7B%22Status%22:Active%7D

Result in Collector:
![iosresult](https://user-images.githubusercontent.com/43046951/45182138-79e23200-b1ee-11e8-84fe-44cd53b86c0d.jpg)

How should iOS be handling the featureSourceURL and featureAttribute parameters of the URL? Is there an issue with the sample URL structure? Or perhaps I am missing a setting that wasn't included in the documentation?

I appreciate your help!

Nicole
