### ISSUE TITLE
Calling Collector from non-ESRI apps

### ISSUE THREAD

**Issue by kyle-harper** [Esri/collector-integration#25]
Hello,

We often integrate both ESRI and non-ESRI apps into our workflows, and one of the apps we use a lot is iFormBuilder. (For some use-cases we prefer Survey123, and in other cases we'll go with iFormBuilder.)

Not sure if it's the same behavior on all platforms, but on iOS the iForm app throws an error when trying to launch any **arcgis-collector://** URL scheme... is this ESRI blocking iFormBuilder from opening Collector (i.e., is there a whitelist of apps that can actually call Collector via the URL scheme), or is it an issue with iFormBuilder?

If ESRI does restrict certain apps from calling Collector, how would we go about requesting apps be added to the whitelist? If there is no such restriction, it would be helpful for me to know and I'll take up the issue again with iFormBuilder. Many thanks!

![alt text](http://ims.dudek.com/cdn/images/iform-collector-launch-error.png "Error Message When Launching Collector from iForm")

**Comment by doug-m** [comment]
We don't explicitly restrict apps from calling us, so as you suggest the problem is likely on the iFormBuilder side. Let us know if you reach a resolution on this.

**Comment by kyle-harper** [comment]
Great - thank you for confirming, Doug! I'll re-open my ticket with iFormBuilder and will post an update on what I hear back before closing this issue.

**Comment by kyle-harper** [comment]
OK - iFormBuilder confirmed they need to allow the arcgis-collector:// URL scheme (which they are currently not doing). I have a call with them this week to discuss having them allow this workflow. I'll go ahead and close this issue - thanks again for the quick response, Doug!
